[build]
  command = "pip install -r requirements.txt && python -m babel.messages.frontend compile -d translations && python freeze.py"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"
