[build]
  command = "pip install -r requirements.txt && pybabel compile -d translations || true && python freeze.py"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"
